name: GitAction

# Define when this workflow should run
on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.13
      
    - name: Build
      run: go build -v ./...

    - name: Login To Dockerhub
      uses: docker/login-action@v1
      with:
        username: stting2 # DockerHub 사용자이름
        password: dckr_pat_trCgOnXlPeOxH5ryqM8JHLGoN1E # DockerHub Access Token
    - name: build and release to DockerHub
      env:
        NAME: stting2 # DockerHub 사용자이름
        REPO: agitaction # DockerHub Repository
      run: |
        docker build -t $REPO .
        docker tag $REPO:latest $NAME/$REPO:latest
        docker push $NAME/$REPO:latest
