name: GitAction

# Define when this workflow should run
on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.13
      
    - name: Build
      run: go build -v ./...

    - name: Login To Dockerhub
      uses: docker/login-action@v1
      with:
        username: stting2
        password: dckr_pat_trCgOnXlPeOxH5ryqM8JHLGoN1E
    - name: build and release to DockerHub
      env:
        NAME: stting2
        REPO: agitaction
      run: |
        docker build -t $REPO .
        docker tag $REPO:latest $NAME/$REPO:latest
        docker push $NAME/$REPO:latest

    
    # - name: Set Up Go
    #     uses: actions/setup-go@v2 # Use the v2 version of the setup-go action
    #     with:
    #       go-version: 1.13 # Specify the Go version you want to use

    #   - name: Build
    #     run: go build -v ./...
    #       # You can add additional build steps if needed
          
    #   - name: Login To DockerHub
    #     uses: docker/login-action@v1
    #     with:
    #       username: stting2
    #       password: dckr_pat_trCgOnXlPeOxH5ryqM8JHLGoN1E

    #   - name: Build and Release to DockerHub
    #     env:
    #       NAME: stting2 # Set your application name
    #       REPO: agitaction # Set your Docker repository name
    #     run: |
    #       # Build and release Docker image here
    #       # Example:
    #       docker build -t $NAME/$REPO .
    #       docker tag $NAME/$REPO:latest $NAME/$REPO:latest
    #       docker push $NAME/$REPO:latest

# You should set secrets for DOCKER_USERNAME and DOCKER_PASSWORD in your GitHub repository settings.
